remove concern face
This was causing errors on some windows machines: 

Error : (converted from warning) unable to re-encode 'tab_descriptive.R' line 242
ERROR: unable to collate and parse R files for package 'sitrep'